version: "3.9"
services:
  init:
    build: ./init
    volumes:
      - ./powerpoints:/app/powerpoints
      - slides:/slides
    networks:
      - powerpoint-lookup

  client: # front-end nginx
    build: ./client
    restart: always
    # nginx static files
    volumes:
      - slides:/slides
    ports:
      - "80:80"
    depends_on:
      - server
      - init
    networks:
      - powerpoint-lookup

  server: # back-end nodejs
    build: ./server
    restart: always
    volumes:
      - slides:/slides
    networks:
      - powerpoint-lookup

volumes:
  slides:
    external: false

networks:
  powerpoint-lookup:
    driver: bridge
